-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  email text not null,
  name text,
  role text default 'user', -- 'admin', 'manager', 'user'
  department text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- TEAMS
create table teams (
  id bigint generated by default as identity primary key,
  name text not null,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Teams
alter table teams enable row level security;
create policy "Teams are viewable by authenticated users." on teams for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert teams." on teams for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update teams." on teams for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete teams." on teams for delete using (auth.role() = 'authenticated');


-- PROJECTS
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text default 'Não Iniciado', -- 'Não Iniciado', 'Em Andamento', 'Concluído', 'Suspenso', 'Cancelado'
  start_date date,
  end_date date,
  budget numeric,
  manager_id uuid references profiles(id), -- Optional link to profile
  manager_name text, -- Denormalized for display if needed, or just use join
  priority text default 'Média',
  progress integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  associated_team_ids jsonb default '[]'::jsonb -- Array of team IDs
);

-- RLS for Projects
alter table projects enable row level security;
create policy "Projects are viewable by authenticated users." on projects for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert projects." on projects for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects." on projects for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete projects." on projects for delete using (auth.role() = 'authenticated');

-- TASKS
create table tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  name text not null,
  description text,
  status text default 'Não Iniciada',
  priority text default 'Média',
  dept text, -- department
  responsible text,
  planned_start date,
  planned_end date,
  planned_duration integer,
  percent_complete integer default 0,
  actual_start date,
  actual_end date,
  actual_duration integer,
  group_name text, -- 'Fase/Grupo'
  predecessors jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Tasks
alter table tasks enable row level security;
create policy "Tasks are viewable by authenticated users." on tasks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert tasks." on tasks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update tasks." on tasks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete tasks." on tasks for delete using (auth.role() = 'authenticated');

-- RISKS
create table risks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  description text not null,
  probability text, -- 'Baixa', 'Média', 'Alta'
  impact text, -- 'Baixo', 'Médio', 'Alto'
  mitigation_plan text,
  status text, -- 'Identificado', 'Monitorado', 'Mitigado', 'Ocorreu'
  owner text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Risks
alter table risks enable row level security;
create policy "Risks are viewable by authenticated users." on risks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert risks." on risks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update risks." on risks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete risks." on risks for delete using (auth.role() = 'authenticated');

-- QUALITY CHECKS
create table quality_checks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  item text not null,
  criteria text,
  status text, -- 'Pendente', 'Aprovado', 'Reprovado'
  checked_date date,
  responsible text,
  comments text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Quality Checks
alter table quality_checks enable row level security;
create policy "Quality Checks are viewable by authenticated users." on quality_checks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert quality_checks." on quality_checks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update quality_checks." on quality_checks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete quality_checks." on quality_checks for delete using (auth.role() = 'authenticated');

-- TRIGGER: Create Profile on Signup
-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();