-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table if not exists profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  email text not null,
  name text,
  role text default 'user', 
  status text default 'Ativo',
  department text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table profiles enable row level security;

do $$ begin
  drop policy if exists "Public profiles are viewable by everyone." on profiles;
  drop policy if exists "Users can insert their own profile." on profiles;
  drop policy if exists "Users can update own profile." on profiles;
end $$;

create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- TEAMS
create table if not exists teams (
  id bigint generated by default as identity primary key,
  name text not null,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table teams enable row level security;

do $$ begin
  drop policy if exists "Teams are viewable by authenticated users." on teams;
  drop policy if exists "Authenticated users can insert teams." on teams;
  drop policy if exists "Authenticated users can update teams." on teams;
  drop policy if exists "Authenticated users can delete teams." on teams;
end $$;

create policy "Teams are viewable by authenticated users." on teams for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert teams." on teams for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update teams." on teams for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete teams." on teams for delete using (auth.role() = 'authenticated');

-- PROJECTS
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text default 'Não Iniciado',
  start_date date,
  end_date date,
  budget numeric,
  manager_id uuid references profiles(id),
  manager_name text,
  priority text default 'Média',
  progress integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  associated_team_ids jsonb default '[]'::jsonb
);

alter table projects enable row level security;

do $$ begin
  drop policy if exists "Projects are viewable by authenticated users." on projects;
  drop policy if exists "Authenticated users can insert projects." on projects;
  drop policy if exists "Authenticated users can update projects." on projects;
  drop policy if exists "Authenticated users can delete projects." on projects;
end $$;

create policy "Projects are viewable by authenticated users." on projects for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert projects." on projects for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects." on projects for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete projects." on projects for delete using (auth.role() = 'authenticated');

-- TASKS
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  name text not null,
  description text,
  status text default 'Não Iniciada',
  priority text default 'Média',
  dept text,
  responsible text,
  planned_start date,
  planned_end date,
  planned_duration integer,
  percent_complete integer default 0,
  actual_start date,
  actual_end date,
  actual_duration integer,
  group_name text,
  predecessors jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table tasks enable row level security;

do $$ begin
  drop policy if exists "Tasks are viewable by authenticated users." on tasks;
  drop policy if exists "Authenticated users can insert tasks." on tasks;
  drop policy if exists "Authenticated users can update tasks." on tasks;
  drop policy if exists "Authenticated users can delete tasks." on tasks;
end $$;

create policy "Tasks are viewable by authenticated users." on tasks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert tasks." on tasks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update tasks." on tasks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete tasks." on tasks for delete using (auth.role() = 'authenticated');

-- RISKS
create table if not exists risks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  description text not null,
  probability text,
  impact text,
  mitigation_plan text,
  status text,
  owner text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table risks enable row level security;

do $$ begin
  drop policy if exists "Risks are viewable by authenticated users." on risks;
  drop policy if exists "Authenticated users can insert risks." on risks;
  drop policy if exists "Authenticated users can update risks." on risks;
  drop policy if exists "Authenticated users can delete risks." on risks;
end $$;

create policy "Risks are viewable by authenticated users." on risks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert risks." on risks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update risks." on risks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete risks." on risks for delete using (auth.role() = 'authenticated');

-- QUALITY CHECKS
create table if not exists quality_checks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  item text not null,
  criteria text,
  status text,
  checked_date date,
  responsible text,
  comments text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table quality_checks enable row level security;

do $$ begin
  drop policy if exists "Quality Checks are viewable by authenticated users." on quality_checks;
  drop policy if exists "Authenticated users can insert quality_checks." on quality_checks;
  drop policy if exists "Authenticated users can update quality_checks." on quality_checks;
  drop policy if exists "Authenticated users can delete quality_checks." on quality_checks;
end $$;

create policy "Quality Checks are viewable by authenticated users." on quality_checks for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert quality_checks." on quality_checks for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update quality_checks." on quality_checks for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete quality_checks." on quality_checks for delete using (auth.role() = 'authenticated');

-- ORGANIZATION SETTINGS (New Table)
create table if not exists public.organization_settings (
  id uuid not null default uuid_generate_v4() primary key,
  name text not null default 'Minha Empresa',
  url_slug text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.organization_settings enable row level security;

do $$ begin
  drop policy if exists "Allow read access for all authenticated users" on public.organization_settings;
  drop policy if exists "Allow update access for Admins only" on public.organization_settings;
end $$;

create policy "Allow read access for all authenticated users"
on public.organization_settings for select
using (auth.role() = 'authenticated');

create policy "Allow update access for Admins only"
on public.organization_settings for update
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

-- Init Default Org Settings if empty
insert into public.organization_settings (name, url_slug)
select 'Minha Empresa', 'minha-empresa'
where not exists (select 1 from public.organization_settings);

-- TRIGGER: Create Profile on Signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name')
  on conflict (id) do nothing; -- idempotent insert
  return new;
end;
$$ language plpgsql security definer;

-- Trigger drop/create
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();